name: Build and Release

on:
  push:
    branches: ['main', 'ci']

jobs:
  update-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version_out.outputs.package_version }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-bump and update version
        run: |
          cargo install cargo-bump
          cargo bump

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[skip ci] | chore: version update"

      - id: version_out
        run: echo "package_version=$(cargo pkgid | cut -d '@' -f2)" >> "$GITHUB_OUTPUT"

  build-image:
    runs-on: ubuntu-latest
    needs: update-version

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - env:
          PACKAGE_VERSION: ${{ needs.update-version.outputs.version }}
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            subscribehn
          tags: |
            type=semver,pattern={{version}},value=${{ env.PACKAGE_VERSION }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
